# Generated by Django 2.1.7 on 2021-01-05 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumapp1', '0002_auto_20200508_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textinfo',
            old_name='stext',
            new_name='stextrank',
        ),
        migrations.AddField(
            model_name='textinfo',
            name='stfidf',
            field=models.TextField(default=django.utils.timezone.now, max_length='6000'),
            preserve_default=False,
        ),
    ]
