# Generated by Django 2.1.7 on 2021-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumapp1', '0003_auto_20210106_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinfo',
            name='shumansum',
            field=models.TextField(blank=True, max_length='6000', null=True),
        ),
    ]
