# Generated by Django 2.1.7 on 2021-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumapp1', '0004_textinfo_shumansum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinfo',
            name='shumansum',
            field=models.TextField(max_length='6000', null=True),
        ),
    ]
