# Generated by Django 2.1.7 on 2021-01-05 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumapp1', '0006_textinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinfo',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
